apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-garage-backend
  labels:
    app: python-garage
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-garage
      tier: backend
  template:
    metadata:
      labels:
        app: python-garage
        tier: backend
    spec:
      containers:
      - name: backend
        image: python-garage-backend
        ports:
        - name: http-server
          containerPort: 8080
        env:
        # Replace with your Firebase project ID.
        - name: FIREBASE_PROJECT_ID
          value: 'trusty-splice-230419'
        - name: GAE_USE_SOCKETS_HTTPLIB
          value: 'true'

          
