apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage-backend
  labels:
    app: garage-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: garage-backend
  template:
    metadata:
      labels:
        app: garage-backend
    spec:
      containers:
      - name: backend
        image: python-garage-backend
        ports:
        - name: http-server
          containerPort: 8080
          protocol: TCP
        env:
        # Replace with your Firebase project ID.
        - name: FIREBASE_PROJECT_ID
          value: 'household-iot-277519'
        - name: GAE_USE_SOCKETS_HTTPLIB
          value: 'true'
        - name: PORT
          value: '8080'
