apiVersion: v1
kind: Service
metadata:
  name: python-garage-backend
  labels:
    app: python-garage
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: python-garage
    tier: backend
  ports:
  - port: 8080
    targetPort: http-server
