apiVersion: v1
kind: Service
metadata:
  name: python-garage-backend
  labels:
    app: python-garage
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: python-garage
    tier: backend
  ports:
    - name: http
      port: 80
      targetPort: http-server
    - name: https
      port: 443
      targetPort: http-server