#!/bin/bash

export SETTINGS_FILE=/garage_settings/settings.json
export GOOGLE_APPLICATION_CREDENTIALS=/garage_settings/service_account.json
export BOOTSTRAP_PORT=8080

echo Starting Sizaha device.

# Turn WiFi radio on... just in case.
nmcli radio wifi on

if [[ -f "/garage_settings/settings.json.tmp" ]]; then
  echo Testing device WiFi configuration
  python3 setup_wifi.py
fi

# Check if settings file was generated by bootstrap server.
if [[ -f "/garage_settings/settings.json" ]]; then
  echo Launching Runtime service.
  python3 ./garage_daemon.py
else
  export AP_NAME="Sizaha$RANDOM"
  echo Launching bootstrap WiFi access point with SSID - $AP_NAME
  python3 bootstrap_wifi.py --ssid "$AP_NAME" start

  echo Launching Bootstrap Server
  python3 bootstrap_server.py

  echo Stopping bootstrap Access point
  python3 bootstrap_wifi.py --ssid "$AP_NAME" stop
fi

reboot

